import Link from 'next/link'
import './globals.css'
import { Inter } from 'next/font/google'
import Cabecalho from '@/Components/Cabecalho/page.jsx'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'API',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <Cabecalho/>
        
        {children}

      </body>
    </html>
  )
}
